export default {
  Homeicon: require('../assest/images/Homeicon.png'),
  FixsterLogo:require('../assest/images/FixsterLogo.png'),
  Banner:require('../assest/images/Banner.png'),
  Painting:require('../assest/images/Painting.png'),
  Plumbing:require('../assest/images/Plumbing.png'),
  Electrical:require('../assest/images/Electrical.png'),
  MaskotKota:require('../assest/images/MaskotKota.png'),
  ShamsJan:require('../assest/images/ShamsJan.png'),
  Appliances:require('../assest/images/Appliances.png'),
  Carpentary:require('../assest/images/Carpentary.png'),
  Gardening:require('../assest/images/Gardening.png'),
  Renovation:require('../assest/images/Renovation.png'),
  OtherServices:require('../assest/images/OtherServices.png'),
  Refrigerator:require('../assest/images/Refrigerator.png'),
  Microwave:require('../assest/images/Microwave.png'),
  AirConditioning:require('../assest/images/AirConditioning.png'),
  TVRepair:require('../assest/images/TVRepair.png'),
  ExpertProfile:require('../assest/images/ExpertProfile.png'),
  Vaccum:require('../assest/images/Vaccum.png'),
  Amit:require('../assest/images/Amit.png'),
  Expertprof:require('../assest/images/Expertprof.png'),
  ExpertProfiletwo:require('../assest/images/ExpertProfiletwo.png'),
  ExpertProfiletin:require('../assest/images/ExpertProfiletin.png'),
  Experrofile:require('../assest/images/Experrofile.png'),
  Exp : require('../assest/images/Exp.png'),
  Bookingmen : require('../assest/images/Bookingmen.png'),
  Booknull:require('../assest/images/Booknull.png'),
  Kaitlyn:require('../assest/images/Kaitlyn.png'),
  Gibson:require('../assest/images/Gibson.png'),
  Chloe:require('../assest/images/Chloe.png'),
  Phoebe:require('../assest/images/Phoebe.png'),
  Jack:require('../assest/images/Jack.png'),
  JohnDoe:require('../assest/images/JohnDoe.png'),
  Butler:require('../assest/images/Butler.png'),
  CarRegistration:require('../assest/images/CarRegistration.png'),
  GeneralContractor:require('../assest/images/GeneralContractor.png'),
  Mechanic:require('../assest/images/Mechanic.png'),
  vehicle:require('../assest/images/vehicle.png'),
};
